version: '3'
services:
  mongodb:
    image: mongo:3.4.1
    working_dir: /opt/mongodb
    volumes:
       - /opt/mongodb:/opt/mongodb
    command: sh -c 'mkdir -p /opt/mongodb && mongod --port 27017 --dbpath /opt/mongodb'
    restart: on-failure

  flask:
    build:
      context: ../../
      dockerfile: docker/flaskapi/Dockerfile
    links:
      - mongodb
    ports:
      - "5000:5000"
    restart: on-failure